' Runner for the harness suites. Loaded last; executes every suite, prints the
' verdict and forces a nonzero exit when anything failed (the brs interpreter
' turns that runtime error into exit code 1).

sub Harness_RunAll()
    Test_Stack_Introspection()
    Test_Push_ShowsAndEnters()
    Test_Modal_Push_KeepsPreviousVisible()
    Test_Push_UnknownScreen()
    Test_Push_UnknownScreenLeavesCurrentAlone()
    Test_Pop_RefusesOnSingle()
    Test_Pop_RestoresPrevious()
    Test_Back_Delegates()
    Test_Back_EmptyStack()
    Test_PopTo()
    Test_Transport_Get_ParsesJson()
    Test_Transport_RejectsBadJson()
    Test_Transport_HttpError()
    Test_Transport_Post_ForwardsBody()
    Test_Settings_Defaults()
    Test_Settings_SetServerAddress()
    Test_Settings_UiScaleBounds()
    Test_Settings_PersistsViaRegistry()
    Test_Settings_InMemoryOnlyWithoutRegistry()
    Test_Auth_GuestLogin()
    Test_Auth_GuestIsLocalOnly()
    Test_Auth_DefaultIsLoggedOut()
    Test_Auth_InstancesIndependent()
    Test_Auth_Logout()
    Test_Addons_BuiltInsPresent()
    Test_Addons_BuiltInsProtected()
    Test_Addons_Install()
    Test_Addons_RejectsInvalidManifest()
    Test_Addons_InstallNoAddress()
    Test_Addons_Uninstall()
    Test_Addons_PersistsViaRegistry()
    Test_Addons_CatalogsFlatten()
    Test_Catalog_Manifest()
    Test_Catalog_ManifestRejectsMissingId()
    Test_Catalog_Fetch()
    Test_Catalog_Search()
    Test_Catalog_RejectsMissingMetas()
    Test_Catalog_NoAddress()
    Test_Episodes_GetMetaMovie()
    Test_Episodes_GetMetaSeries()
    Test_Episodes_RejectsSeriesWithoutVideos()
    Test_Episodes_Seasons()
    Test_Episodes_EpisodesForSeason()
    Test_Episodes_ResolveVideoId()
    Test_Library_AddAndListSaved()
    Test_Library_RemoveSaved()
    Test_Library_ContinueWatchingOrdering()
    Test_Library_RemovePosition()
    Test_Library_ResumeFor()
    Test_Library_PersistsViaRegistry()
    Test_Library_InMemoryOnlyWithoutRegistry()
    Test_Playback_Streams()
    Test_Playback_StreamsValidates()
    Test_Playback_StreamsNoAddress()
    Test_Playback_DirectStreamResolvesAsIs()
    Test_Playback_CreateSessionForwardsFileIdx()
    Test_Playback_TorrentResolvesThroughServer()
    Test_Playback_TorrentWithoutServerAddress()
    Test_Playback_PlaybackUrl()
    Test_Playback_Heartbeat()
    Harness_Finish()
end sub

Harness_RunAll()

if m.failed > 0
    bad = invalid
    x = bad.poison
end if