' WatchedCodec unit tests.
'
' The decoder is pure BrightScript logic over byte arrays, so it runs fully in
' the interpreter. The fixture corpus lives in watchedcodec.fixtures.brs
' (generated by scripts/gen-watched-fixtures.js from Node's own zlib, the
' source of truth the stremio server uses on its side).

function TestWatchedIds(ids as object) as object
    return { id: ids[4], season: 1, release: 2 }
end function

sub Test_WatchedCodec_DecodesKnownPayload()
    Harness_Suite("WatchedCodec decodes the stremio-core sample payload")
    codec = WatchedCodec()

    ' The raw base64 payload (eJyTZwAAAEAAIA==) is the zlib bytes the server
    ' wrote: 78 9c header, deflate stream, trailing Adler-32.
    Harness_Equal(ToHexList(codec.Base64Decode("eJyTZwAAAEAAIA==")), "78 9c 93 67 00 00 00 40 00 20", "base64 payload decodes to the zlib bytes")

    bytes = codec.Base64Decode("eJyTZwAAAEAAIA==")
    inflated = codec.Inflate(bytes)
    Harness_Ok(inflated <> invalid, "zlib stream inflates")
    Harness_Equal(inflated.Count(), 2, "two decompressed bytes")
    Harness_Equal(inflated[0], 31, "first byte 0x1f")
    Harness_Equal(inflated[1], 0, "second byte 0x00")

    ids = ["tt2934286:1:1", "tt2934286:1:2", "tt2934286:1:3", "tt2934286:1:4", "tt2934286:1:5"]
    watched = codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", ids)
    Harness_Equal(watched.Count(), 5, "all five episodes watched")
    for each id in ids
        Harness_Ok(watched[id], "episode " + id + " watched")
    end for
end sub

function ToHexList(values as object) as string
    hex = "0123456789abcdef"
    out = ""
    for each v in values
        if out <> "" then out = out + " "
        hi = v \ 16
        lo = v mod 16
        out = out + hex.Mid(hi, 1) + hex.Mid(lo, 1)
    end for
    return out
end function

sub Test_WatchedCodec_Base64EdgeCases()
    Harness_Suite("WatchedCodec.Base64Decode edge cases")
    codec = WatchedCodec()

    Harness_Equal(codec.Base64Decode("").Count(), 0, "empty string decodes empty")
    Harness_Equal(ToHexList(codec.Base64Decode("TWFu")), "4d 61 6e", "TWFu decodes Man")
    Harness_Equal(ToHexList(codec.Base64Decode("TWE=")), "4d 61", "TWE= decodes Ma")
    Harness_Equal(ToHexList(codec.Base64Decode("TQ==")), "4d", "TQ== decodes M")
    Harness_Equal(ToHexList(codec.Base64Decode("AAA=")), "00 00", "AAA= decodes two zeros")
    Harness_Equal(codec.Base64Decode("A"), invalid, "single-char input rejected")
    Harness_Equal(codec.Base64Decode("===="), invalid, "padding-only input rejected")
    Harness_Equal(codec.Base64Decode("ab!!cd"), invalid, "foreign characters rejected")
    Harness_Equal(codec.Base64Decode("a===="), invalid, "excess padding rejected")
end sub

sub Test_WatchedCodec_FixturesDecodeExpectedBits()
    Harness_Suite("WatchedCodec decodes the generated fixture corpus")
    codec = WatchedCodec()
    for each fixture in WatchedCodecFixtures()
        covered = false
        watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
        Harness_Equal(watched.Count(), fixture.expected.Count(), fixture.note + ": watched count")
        for each id in fixture.ids
            Harness_Ok(watched.DoesExist(id) = ExpectedHas(fixture.expected, idIndex(id, fixture.ids)), fixture.note + ": " + id + " matched")
        end for
    end for
end sub

function idIndex(id as string, ids as object) as integer
    for i = 0 to ids.Count() - 1
        if ids[i] = id then return i
    end for
    return -1
end function

function ExpectedHas(expected as object, index as integer) as boolean
    for each e in expected
        if e = index then return true
    end for
    return false
end function

sub Test_WatchedCodec_BlockBoundaries()
    Harness_Suite("WatchedCodec handles multi-byte payloads across block boundaries")
    codec = WatchedCodec()
    fixtures = WatchedCodecFixtures()
    sparse = invalid
    boundary = invalid
    for each fixture in fixtures
        if fixture.note = "sparse 64-bit payload" then sparse = fixture
        if fixture.note = "81-bit block-boundary payload" then boundary = fixture
    end for

    watched = codec.WatchedDecode(sparse.bitfield, sparse.ids)
    Harness_Equal(watched.Count(), sparse.expected.Count(), "sparse: 4 of 64 watched")
    for each index in sparse.expected
        Harness_Ok(watched.DoesExist(sparse.ids[index]), "sparse index " + index.ToStr() + " watched")
    end for

    watched2 = codec.WatchedDecode(boundary.bitfield, boundary.ids)
    Harness_Equal(watched2.Count(), boundary.expected.Count(), "81-bit boundary: 6 watched")
    for each index in boundary.expected
        Harness_Ok(watched2.DoesExist(boundary.ids[index]), "boundary index " + index.ToStr() + " watched")
    end for

    watched3 = codec.WatchedDecode("tt9990009:2:3:24:eJwBAwD8/wFAAgAAAAA=", boundary.ids)

    ' The codec is positional: a bitboard decodes against the caller's orderered
    ' episode list, so the same payload re-checked against a foreign series'
    ' (longer) list still maps bits to whatever ids sit at those positions.
    Harness_Equal(watched3.Count(), 3, "stored payload against a longer foreign list maps 3 bits")
    Harness_Ok(watched3.DoesExist(boundary.ids[0]), "foreign list position 0 exposed")
    Harness_Ok(watched3.DoesExist(boundary.ids[14]), "foreign list position 14 exposed")
    Harness_Ok(watched3.DoesExist(boundary.ids[17]), "foreign list position 17 exposed")
end sub

sub Test_WatchedCodec_StoredBlock()
    Harness_Suite("WatchedCodec inflates a stored (BTYPE=00) block")
    codec = WatchedCodec()
    fixture = invalid
    for each f in WatchedCodecFixtures()
        if f.note = "stored block payload" then fixture = f
    end for
    Harness_Ok(fixture <> invalid, "stored fixture present")

    watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
    Harness_Equal(watched.Count(), fixture.expected.Count(), "stored: 3 watched")
    for each index in fixture.expected
        Harness_Ok(watched.DoesExist(fixture.ids[index]), "stored index " + index.ToStr() + " watched")
    end for
end sub

sub Test_WatchedCodec_DynamicBlockWithMatches()
    Harness_Suite("WatchedCodec inflates a dynamic (BTYPE=10) block with back-references")
    codec = WatchedCodec()
    fixture = invalid
    for each f in WatchedCodecFixtures()
        if f.note = "dynamic block with length/distance matches" then fixture = f
    end for
    Harness_Ok(fixture <> invalid, "dynamic fixture present")

    watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
    Harness_Equal(watched.Count(), fixture.expected.Count(), "dynamic: watched count matches expose window")
    for each index in fixture.expected
        Harness_Ok(watched.DoesExist(fixture.ids[index]), "dynamic index " + index.ToStr() + " watched")
    end for
end sub

sub Test_WatchedCodec_HandlesEmptyAndInvalid()
    Harness_Suite("WatchedCodec never crashes on empty or malformed input")
    codec = WatchedCodec()
    sample = ["tt2934286:1:1", "tt2934286:1:2"]

    Harness_Equal(codec.WatchedDecode("", sample).Count(), 0, "empty bitfield")
    Harness_Equal(codec.WatchedDecode(invalid, sample).Count(), 0, "invalid bitfield")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", []).Count(), 0, "no episode ids")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", invalid).Count(), 0, "invalid episode ids")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", "not-an-array").Count(), 0, "non-array episode ids")
    Harness_Equal(codec.WatchedDecode("not-a-bitfield", sample).Count(), 0, "no payload prefix")
    Harness_Equal(codec.WatchedDecode("tt:5:!!!", sample).Count(), 0, "foreign payload characters")
    Harness_Equal(codec.WatchedDecode("tt:abc:////", sample).Count(), 0, "non-numeric length")
    Harness_Equal(codec.WatchedDecode("tt:5:", sample).Count(), 0, "empty payload")
    Harness_Equal(codec.WatchedDecode("tt:5:eJyT", sample).Count(), 0, "truncated payload")
end sub

sub Test_WatchedCodec_ClampsToEpisodeList()
    Harness_Suite("WatchedCodec clamps exposed bits to the episode list and data")
    codec = WatchedCodec()
    fixtures = WatchedCodecFixtures()
    clamp = invalid
    truncated = invalid
    for each fixture in fixtures
        if fixture.note = "exposed bits clamp to episode list" then clamp = fixture
        if fixture.note = "bitfield shorter than its claimed length" then truncated = fixture
    end for

    watched = codec.WatchedDecode(clamp.bitfield, clamp.ids)
    Harness_Equal(watched.Count(), clamp.expected.Count(), "clamp: 2 ids watched from a 5-bit field")
    for each index in clamp.expected
        Harness_Ok(watched.DoesExist(clamp.ids[index]), "clamp id " + index.ToStr() + " watched")
    end for

    watched2 = codec.WatchedDecode(truncated.bitfield, truncated.ids)
    Harness_Equal(watched2.Count(), truncated.expected.Count(), "truncated: only decodable bits exposed")
    for each index in truncated.expected
        Harness_Ok(watched2.DoesExist(truncated.ids[index]), "truncated id " + index.ToStr() + " watched")
    end for
end sub
sub Test_WatchedCodec_EncodeRoundTrips()
    Harness_Suite("WatchedCodec encodes a set to the account silhouette and back")
    codec = WatchedCodec()
    ids = ["tt2934286:1:1", "tt2934286:1:2", "tt2934286:1:3", "tt2934286:1:4", "tt2934286:1:5"]
    watched = { "tt2934286:1:2": true, "tt2934286:1:4": true }

    encoded = codec.WatchedEncode(ids, watched, "tt2934286:1:4")
    Harness_Ok(encoded <> "", "encode yields a string")
    parts = encoded.Split(":")
    Harness_Ok(parts.Count() >= 3, "silhouette is lastId:length:payload")
    prefix = ""
    for i = 0 to parts.Count() - 3
        if i > 0 then prefix = prefix + ":"
        prefix = prefix + parts[i]
    end for
    Harness_Equal(prefix, "tt2934286:1:4", "lastVideoId slot reported (colons kept)")
    Harness_Equal(parts[parts.Count() - 2], "4", "length field is the last watched index + 1")

    decoded = codec.WatchedDecode(encoded, ids)
    Harness_Equal(decoded.Count(), 2, "decode back recovers the set size")
    Harness_Ok(decoded["tt2934286:1:2"], "first watched id recovered")
    Harness_Ok(decoded["tt2934286:1:4"], "second watched id recovered")
    Harness_Ok(decoded["tt2934286:1:1"] = invalid, "unwatched id stays out")
end sub

sub Test_WatchedCodec_EncodeCanonicalAnchor()
    Harness_Suite("WatchedCodec encode uses the canonical last-watched anchor, not the list size")
    codec = WatchedCodec()
    ids = ["tt2934286:1:1", "tt2934286:1:2", "tt2934286:1:3", "tt2934286:1:4", "tt2934286:1:5"]

    watched = { "tt2934286:1:2": true, "tt2934286:1:4": true }
    encoded = codec.WatchedEncode(ids, watched, "tt2934286:1:4")
    parts = encoded.Split(":")
    prefix = ""
    for i = 0 to parts.Count() - 3
        if i > 0 then prefix = prefix + ":"
        prefix = prefix + parts[i]
    end for
    anchorLength = parts[parts.Count() - 2]
    Harness_Equal(prefix, "tt2934286:1:4", "anchor id is the last watched episode")
    Harness_Equal(anchorLength, (codec.IndexInIds(ids, prefix) + 1).ToStr(), "anchorLength stays index-of-anchor + 1 (canonical)")
    Harness_Ok(codec.WatchedDecode(encoded, ids)["tt2934286:1:4"], "the anchor episode decodes watched")

    watchedTail = { "tt2934286:1:1": true, "tt2934286:1:5": true }
    encodedTail = codec.WatchedEncode(ids, watchedTail, "tt2934286:1:5")
    partsTail = encodedTail.Split(":")
    Harness_Equal(partsTail[partsTail.Count() - 2], "5", "a last-watched episode at the tail keeps the full-length anchor")
    decodedTail = codec.WatchedDecode(encodedTail, ids)
    Harness_Ok(decodedTail["tt2934286:1:1"], "earlier bit survives under a tail anchor")
    Harness_Ok(decodedTail["tt2934286:1:5"], "tail bit survives under a tail anchor")

    encodedEmpty = codec.WatchedEncode(ids, {}, "tt2934286:1:4")
    partsEmpty = encodedEmpty.Split(":")
    prefixEmpty = ""
    for i = 0 to partsEmpty.Count() - 3
        if i > 0 then prefixEmpty = prefixEmpty + ":"
        prefixEmpty = prefixEmpty + partsEmpty[i]
    end for
    Harness_Equal(prefixEmpty, "tt2934286:1:4", "an empty set keeps the in-list anchor id")
    Harness_Equal(partsEmpty[partsEmpty.Count() - 2], "4", "the anchor length still tracks its index + 1")
    Harness_Equal(codec.WatchedDecode(encodedEmpty, ids).Count(), 0, "the all-zero payload decodes to nothing watched")

    encodedAbsent = codec.WatchedEncode(ids, {}, "tt999:9:9")
    partsAbsent = encodedAbsent.Split(":")
    prefixAbsent = ""
    for i = 0 to partsAbsent.Count() - 3
        if i > 0 then prefixAbsent = prefixAbsent + ":"
        prefixAbsent = prefixAbsent + partsAbsent[i]
    end for
    Harness_Equal(prefixAbsent, "tt2934286:1:1", "an id missing from the list falls back to the first id")
    Harness_Equal(partsAbsent[partsAbsent.Count() - 2], "1", "the fallback anchor carries length 1")
end sub

sub Test_WatchedCodec_DecodesCanonicalBitfield()
    Harness_Suite("WatchedCodec decodes the canonical stremio bitfield payload")
    codec = WatchedCodec()

    ' Node's own zlib produced eJz7//8/AAX9Av4= from three 0xff bytes — the same
    ' payload the stremio tests embed as tt7767422:3:8:24:eJz7//8/AAX9Av4=. The
    ' anchor is the series' 24th episode (index 23), so anchorLength == 24 is the
    ' canonical expectation, and every one of the 24 bits is set.
    ids = ["tt7767422:1:1", "tt7767422:1:2", "tt7767422:1:3", "tt7767422:1:4", "tt7767422:1:5", "tt7767422:1:6", "tt7767422:1:7", "tt7767422:1:8", "tt7767422:2:1", "tt7767422:2:2", "tt7767422:2:3", "tt7767422:2:4", "tt7767422:2:5", "tt7767422:2:6", "tt7767422:2:7", "tt7767422:2:8", "tt7767422:3:1", "tt7767422:3:2", "tt7767422:3:3", "tt7767422:3:4", "tt7767422:3:5", "tt7767422:3:6", "tt7767422:3:7", "tt7767422:3:8"]
    Harness_Equal(codec.IndexInIds(ids, "tt7767422:3:8"), 23, "the fixture's anchor sits at index 23")

    canonical = "tt7767422:3:8:24:eJz7//8/AAX9Av4="
    watched = codec.WatchedDecode(canonical, ids)
    Harness_Equal(watched.Count(), 24, "all 24 episodes watched")
    Harness_Ok(watched["tt7767422:3:8"], "the anchor episode is watched")
    Harness_Ok(watched["tt7767422:1:1"], "the first episode is watched")

    canonicalParts = canonical.Split(":")
    Harness_Equal(canonicalParts[canonicalParts.Count() - 2], "24", "anchorLength parses as index-of-anchor + 1")
end sub

sub Test_WatchedCodec_EncodeIsValidZlib()
    Harness_Suite("WatchedCodec encode is a conformant zlib stream any inflater accepts")
    codec = WatchedCodec()
    ids = ["tt1:1:1", "tt1:1:2", "tt1:1:3", "tt1:1:4", "tt1:1:5", "tt1:1:6", "tt1:1:7", "tt1:1:8", "tt1:1:9", "tt1:1:10"]
    watched = { "tt1:1:1": true, "tt1:1:10": true }
    encoded = codec.WatchedEncode(ids, watched, "tt1:1:10")
    parts = encoded.Split(":")
    bytes = codec.Base64Decode(parts[parts.Count() - 1])
    Harness_Equal(bytes[0], 120, "zlib CMF byte 0x78")
    Harness_Equal(bytes[1], 1, "zlib FLG byte 0x01 (CMF*256+FLG mod 31 = 0)")
    inflated = codec.Inflate(bytes)
    Harness_Equal(inflated.Count(), 2, "stored block inflates to ceil(10/8) bytes")
    Harness_Equal(inflated[0], 1, "bit 0 (episode 1) set")
    Harness_Equal(inflated[1], 2, "bit 9 (episode 10) set")
end sub

sub Test_WatchedCodec_EncodeEmptySet()
    Harness_Suite("WatchedCodec encodes an empty set as a zero bitfield")
    codec = WatchedCodec()
    ids = ["tt1:1:1", "tt1:1:2", "tt1:1:3"]
    encoded = codec.WatchedEncode(ids, {}, "tt1:1:1")
    decoded = codec.WatchedDecode(encoded, ids)
    Harness_Equal(decoded.Count(), 0, "nothing watched decodes back")
    parts = encoded.Split(":")
    Harness_Equal(parts[parts.Count() - 2], "1", "empty set anchors on index 0 with length 1")
    bytes = codec.Base64Decode(parts[parts.Count() - 1])
    inflated = codec.Inflate(bytes)
    Harness_Equal(inflated[0], 0, "all bits zero")
end sub

sub Test_WatchedCodec_EncodeGuards()
    Harness_Suite("WatchedCodec encodes refuse invalid inputs")
    codec = WatchedCodec()
    Harness_Equal(codec.WatchedEncode([], {}, "tt"), "", "empty list refused")
    Harness_Equal(codec.WatchedEncode(["tt"], {}, ""), "", "empty lastVideoId refused")
    Harness_Equal(codec.WatchedEncode(invalid, {}, "tt"), "", "invalid list refused")
end sub
