' WatchedCodec unit tests.
'
' The decoder is pure BrightScript logic over byte arrays, so it runs fully in
' the interpreter. The fixture corpus lives in watchedcodec.fixtures.brs
' (generated by scripts/gen-watched-fixtures.js from Node's own zlib, the
' source of truth the stremio server uses on its side).

function TestWatchedIds(ids as object) as object
    return { id: ids[4], season: 1, release: 2 }
end function

sub Test_WatchedCodec_DecodesKnownPayload()
    Harness_Suite("WatchedCodec decodes the stremio-core sample payload")
    codec = WatchedCodec()

    ' The raw base64 payload (eJyTZwAAAEAAIA==) is the zlib bytes the server
    ' wrote: 78 9c header, deflate stream, trailing Adler-32.
    Harness_Equal(ToHexList(codec.Base64Decode("eJyTZwAAAEAAIA==")), "78 9c 93 67 00 00 00 40 00 20", "base64 payload decodes to the zlib bytes")

    bytes = codec.Base64Decode("eJyTZwAAAEAAIA==")
    inflated = codec.Inflate(bytes)
    Harness_Ok(inflated <> invalid, "zlib stream inflates")
    Harness_Equal(inflated.Count(), 2, "two decompressed bytes")
    Harness_Equal(inflated[0], 31, "first byte 0x1f")
    Harness_Equal(inflated[1], 0, "second byte 0x00")

    ids = ["tt2934286:1:1", "tt2934286:1:2", "tt2934286:1:3", "tt2934286:1:4", "tt2934286:1:5"]
    watched = codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", ids)
    Harness_Equal(watched.Count(), 5, "all five episodes watched")
    for each id in ids
        Harness_Ok(watched[id], "episode " + id + " watched")
    end for
end sub

function ToHexList(values as object) as string
    hex = "0123456789abcdef"
    out = ""
    for each v in values
        if out <> "" then out = out + " "
        hi = v \ 16
        lo = v mod 16
        out = out + hex.Mid(hi, 1) + hex.Mid(lo, 1)
    end for
    return out
end function

sub Test_WatchedCodec_Base64EdgeCases()
    Harness_Suite("WatchedCodec.Base64Decode edge cases")
    codec = WatchedCodec()

    Harness_Equal(codec.Base64Decode("").Count(), 0, "empty string decodes empty")
    Harness_Equal(ToHexList(codec.Base64Decode("TWFu")), "4d 61 6e", "TWFu decodes Man")
    Harness_Equal(ToHexList(codec.Base64Decode("TWE=")), "4d 61", "TWE= decodes Ma")
    Harness_Equal(ToHexList(codec.Base64Decode("TQ==")), "4d", "TQ== decodes M")
    Harness_Equal(ToHexList(codec.Base64Decode("AAA=")), "00 00", "AAA= decodes two zeros")
    Harness_Equal(codec.Base64Decode("A"), invalid, "single-char input rejected")
    Harness_Equal(codec.Base64Decode("===="), invalid, "padding-only input rejected")
    Harness_Equal(codec.Base64Decode("ab!!cd"), invalid, "foreign characters rejected")
    Harness_Equal(codec.Base64Decode("a===="), invalid, "excess padding rejected")
end sub

sub Test_WatchedCodec_FixturesDecodeExpectedBits()
    Harness_Suite("WatchedCodec decodes the generated fixture corpus")
    codec = WatchedCodec()
    for each fixture in WatchedCodecFixtures()
        covered = false
        watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
        Harness_Equal(watched.Count(), fixture.expected.Count(), fixture.note + ": watched count")
        for each id in fixture.ids
            Harness_Ok(watched.DoesExist(id) = ExpectedHas(fixture.expected, idIndex(id, fixture.ids)), fixture.note + ": " + id + " matched")
        end for
    end for
end sub

function idIndex(id as string, ids as object) as integer
    for i = 0 to ids.Count() - 1
        if ids[i] = id then return i
    end for
    return -1
end function

function ExpectedHas(expected as object, index as integer) as boolean
    for each e in expected
        if e = index then return true
    end for
    return false
end function

sub Test_WatchedCodec_BlockBoundaries()
    Harness_Suite("WatchedCodec handles multi-byte payloads across block boundaries")
    codec = WatchedCodec()
    fixtures = WatchedCodecFixtures()
    sparse = invalid
    boundary = invalid
    for each fixture in fixtures
        if fixture.note = "sparse 64-bit payload" then sparse = fixture
        if fixture.note = "81-bit block-boundary payload" then boundary = fixture
    end for

    watched = codec.WatchedDecode(sparse.bitfield, sparse.ids)
    Harness_Equal(watched.Count(), sparse.expected.Count(), "sparse: 4 of 64 watched")
    for each index in sparse.expected
        Harness_Ok(watched.DoesExist(sparse.ids[index]), "sparse index " + index.ToStr() + " watched")
    end for

    watched2 = codec.WatchedDecode(boundary.bitfield, boundary.ids)
    Harness_Equal(watched2.Count(), boundary.expected.Count(), "81-bit boundary: 6 watched")
    for each index in boundary.expected
        Harness_Ok(watched2.DoesExist(boundary.ids[index]), "boundary index " + index.ToStr() + " watched")
    end for

    watched3 = codec.WatchedDecode("tt9990009:2:3:24:eJwBAwD8/wFAAgAAAAA=", boundary.ids)

    ' The codec is positional: a bitboard decodes against the caller's orderered
    ' episode list, so the same payload re-checked against a foreign series'
    ' (longer) list still maps bits to whatever ids sit at those positions.
    Harness_Equal(watched3.Count(), 3, "stored payload against a longer foreign list maps 3 bits")
    Harness_Ok(watched3.DoesExist(boundary.ids[0]), "foreign list position 0 exposed")
    Harness_Ok(watched3.DoesExist(boundary.ids[14]), "foreign list position 14 exposed")
    Harness_Ok(watched3.DoesExist(boundary.ids[17]), "foreign list position 17 exposed")
end sub

sub Test_WatchedCodec_StoredBlock()
    Harness_Suite("WatchedCodec inflates a stored (BTYPE=00) block")
    codec = WatchedCodec()
    fixture = invalid
    for each f in WatchedCodecFixtures()
        if f.note = "stored block payload" then fixture = f
    end for
    Harness_Ok(fixture <> invalid, "stored fixture present")

    watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
    Harness_Equal(watched.Count(), fixture.expected.Count(), "stored: 3 watched")
    for each index in fixture.expected
        Harness_Ok(watched.DoesExist(fixture.ids[index]), "stored index " + index.ToStr() + " watched")
    end for
end sub

sub Test_WatchedCodec_DynamicBlockWithMatches()
    Harness_Suite("WatchedCodec inflates a dynamic (BTYPE=10) block with back-references")
    codec = WatchedCodec()
    fixture = invalid
    for each f in WatchedCodecFixtures()
        if f.note = "dynamic block with length/distance matches" then fixture = f
    end for
    Harness_Ok(fixture <> invalid, "dynamic fixture present")

    watched = codec.WatchedDecode(fixture.bitfield, fixture.ids)
    Harness_Equal(watched.Count(), fixture.expected.Count(), "dynamic: watched count matches expose window")
    for each index in fixture.expected
        Harness_Ok(watched.DoesExist(fixture.ids[index]), "dynamic index " + index.ToStr() + " watched")
    end for
end sub

sub Test_WatchedCodec_HandlesEmptyAndInvalid()
    Harness_Suite("WatchedCodec never crashes on empty or malformed input")
    codec = WatchedCodec()
    sample = ["tt2934286:1:1", "tt2934286:1:2"]

    Harness_Equal(codec.WatchedDecode("", sample).Count(), 0, "empty bitfield")
    Harness_Equal(codec.WatchedDecode(invalid, sample).Count(), 0, "invalid bitfield")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", []).Count(), 0, "no episode ids")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", invalid).Count(), 0, "invalid episode ids")
    Harness_Equal(codec.WatchedDecode("tt2934286:1:5:5:eJyTZwAAAEAAIA==", "not-an-array").Count(), 0, "non-array episode ids")
    Harness_Equal(codec.WatchedDecode("not-a-bitfield", sample).Count(), 0, "no payload prefix")
    Harness_Equal(codec.WatchedDecode("tt:5:!!!", sample).Count(), 0, "foreign payload characters")
    Harness_Equal(codec.WatchedDecode("tt:abc:////", sample).Count(), 0, "non-numeric length")
    Harness_Equal(codec.WatchedDecode("tt:5:", sample).Count(), 0, "empty payload")
    Harness_Equal(codec.WatchedDecode("tt:5:eJyT", sample).Count(), 0, "truncated payload")
end sub

sub Test_WatchedCodec_ClampsToEpisodeList()
    Harness_Suite("WatchedCodec clamps exposed bits to the episode list and data")
    codec = WatchedCodec()
    fixtures = WatchedCodecFixtures()
    clamp = invalid
    truncated = invalid
    for each fixture in fixtures
        if fixture.note = "exposed bits clamp to episode list" then clamp = fixture
        if fixture.note = "bitfield shorter than its claimed length" then truncated = fixture
    end for

    watched = codec.WatchedDecode(clamp.bitfield, clamp.ids)
    Harness_Equal(watched.Count(), clamp.expected.Count(), "clamp: 2 ids watched from a 5-bit field")
    for each index in clamp.expected
        Harness_Ok(watched.DoesExist(clamp.ids[index]), "clamp id " + index.ToStr() + " watched")
    end for

    watched2 = codec.WatchedDecode(truncated.bitfield, truncated.ids)
    Harness_Equal(watched2.Count(), truncated.expected.Count(), "truncated: only decodable bits exposed")
    for each index in truncated.expected
        Harness_Ok(watched2.DoesExist(truncated.ids[index]), "truncated id " + index.ToStr() + " watched")
    end for
end sub